swagger: "2.0"
info:
  title: Checkpoint Openshfit API
  description: Backend presenting rules for Checkpoint based on ocp definition
  version: ""
host: localhost:8080
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /v1/egress:
    get:
      tags:
      - rules
      summary: egressList rules
      description: List all egress rules
      operationId: rules#egressList
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/RulesEgressListResponseBody'
      schemes:
      - http
  /v1/ingress:
    get:
      tags:
      - rules
      summary: ingressList rules
      description: List all ingress rules
      operationId: rules#ingressList
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/RulesIngressListResponseBody'
      schemes:
      - http
definitions:
  RulesEgressListResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.ruleset; view=default'
    type: object
    properties:
      description:
        type: string
        description: description of the object
        default: ""
        example: jsa
        maxLength: 100
      objects:
        type: array
        items:
          $ref: '#/definitions/StoredCheckpointRuleResponseBody'
        description: Rulesets
        example:
        - description: nif
          id: ae5
          name: rcw
          ranges:
          - Velit ipsum magnam enim minima.
          - Magni rerum voluptas voluptatem ex ut.
        - description: nif
          id: ae5
          name: rcw
          ranges:
          - Velit ipsum magnam enim minima.
          - Magni rerum voluptas voluptatem ex ut.
        - description: nif
          id: ae5
          name: rcw
          ranges:
          - Velit ipsum magnam enim minima.
          - Magni rerum voluptas voluptatem ex ut.
        - description: nif
          id: ae5
          name: rcw
          ranges:
          - Velit ipsum magnam enim minima.
          - Magni rerum voluptas voluptatem ex ut.
      version:
        type: string
        description: version of the ruleset
        default: "1.0"
        example: 3u3
        maxLength: 8
    description: EgressListResponseBody result type (default view)
    example:
      description: oxt
      objects:
      - description: nif
        id: ae5
        name: rcw
        ranges:
        - Velit ipsum magnam enim minima.
        - Magni rerum voluptas voluptatem ex ut.
      - description: nif
        id: ae5
        name: rcw
        ranges:
        - Velit ipsum magnam enim minima.
        - Magni rerum voluptas voluptatem ex ut.
      - description: nif
        id: ae5
        name: rcw
        ranges:
        - Velit ipsum magnam enim minima.
        - Magni rerum voluptas voluptatem ex ut.
      - description: nif
        id: ae5
        name: rcw
        ranges:
        - Velit ipsum magnam enim minima.
        - Magni rerum voluptas voluptatem ex ut.
      version: h17
  RulesIngressListResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.ruleset; view=default'
    type: object
    properties:
      description:
        type: string
        description: description of the object
        default: ""
        example: el0
        maxLength: 100
      objects:
        type: array
        items:
          $ref: '#/definitions/StoredCheckpointRuleResponseBody'
        description: Rulesets
        example:
        - description: nif
          id: ae5
          name: rcw
          ranges:
          - Velit ipsum magnam enim minima.
          - Magni rerum voluptas voluptatem ex ut.
        - description: nif
          id: ae5
          name: rcw
          ranges:
          - Velit ipsum magnam enim minima.
          - Magni rerum voluptas voluptatem ex ut.
        - description: nif
          id: ae5
          name: rcw
          ranges:
          - Velit ipsum magnam enim minima.
          - Magni rerum voluptas voluptatem ex ut.
      version:
        type: string
        description: version of the ruleset
        default: "1.0"
        example: kvo
        maxLength: 8
    description: IngressListResponseBody result type (default view)
    example:
      description: 3ci
      objects:
      - description: nif
        id: ae5
        name: rcw
        ranges:
        - Velit ipsum magnam enim minima.
        - Magni rerum voluptas voluptatem ex ut.
      - description: nif
        id: ae5
        name: rcw
        ranges:
        - Velit ipsum magnam enim minima.
        - Magni rerum voluptas voluptatem ex ut.
      - description: nif
        id: ae5
        name: rcw
        ranges:
        - Velit ipsum magnam enim minima.
        - Magni rerum voluptas voluptatem ex ut.
      version: 0sq
  StoredCheckpointRuleResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.rule; view=default'
    type: object
    properties:
      description:
        type: string
        description: description of the object
        default: ""
        example: n67
        maxLength: 100
      id:
        type: string
        description: uuid of the object
        default: ""
        example: 8cd
        maxLength: 100
      name:
        type: string
        description: Return the name of the record
        default: generic-object
        example: yjv
        maxLength: 100
      ranges:
        type: array
        items:
          type: string
          example: Amet molestiae tenetur sapiente.
        description: Ip adresss
        example:
        - Nihil voluptas rerum.
        - Velit accusamus quia omnis asperiores sit aut.
        - Molestias qui iure rem perspiciatis harum qui.
    description: A StoredCheckpointRules describes a one rules (default view)
    example:
      description: d5y
      id: r8p
      name: k4g
      ranges:
      - Enim quia.
      - Architecto animi.
      - Quasi non perspiciatis.
      - Ut reprehenderit eligendi cum facere aliquam.
